# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NASA PROJECT CI

on:
  push:
    branches: [ Access ]
  pull_request:
    branches: [ Access ]

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      CI: true
      MONGO_URL: mongodb://localhost/test

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ['4.2', '4.4']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Use MongoDB from Github Actions
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    
    - run: yarn
    - run: npm run build --prefix client
    - run: yarn test